#!/usr/bin/env python3
"""
Generate CRC32/CRC32C as pure XOR network BSV code.

For a fixed 8-byte (64-bit) input, CRC is a linear function over GF(2).
Each output bit can be expressed as XOR of a subset of input bits,
plus an optional constant 1.

This eliminates all muxes — the result is a depth ~log2(N) XOR tree.
"""

from __future__ import annotations

from pathlib import Path

# Reflected polynomials
CRC32_POLY = 0xEDB88320
CRC32C_POLY = 0x82F63B78

CONST_BIT = 64  # index for the constant term


def compute_xor_matrix(poly: int) -> list[int]:
    """
    Symbolically simulate reflected CRC32 over 64 input bits.

    Each of the 32 output bits is represented as a bitmask:
      bits [63:0]  — which input bits participate (XOR)
      bit  [64]    — whether to XOR with constant 1

    Returns a list of 32 bitmasks (output[0] .. output[31]).
    """
    # Initial CRC state: 0xFFFFFFFF → each bit is constant 1
    crc = [(1 << CONST_BIT) for _ in range(32)]

    for j in range(64):
        # feedback = crc[0] XOR input[j]
        feedback = crc[0] ^ (1 << j)

        new_crc = [0] * 32
        for i in range(31):
            new_crc[i] = crc[i + 1]
            if poly & (1 << i):
                new_crc[i] ^= feedback
        # bit 31: (crc >> 1)[31] = 0, then XOR poly[31] & feedback
        new_crc[31] = feedback if (poly & (1 << 31)) else 0

        crc = new_crc

    # Final inversion: XOR each bit with 1
    for i in range(32):
        crc[i] ^= 1 << CONST_BIT

    return crc


def bitmask_to_xor_expr(mask: int, var: str = "d") -> str:
    """Convert a symbolic bitmask to a BSV XOR expression."""
    terms: list[str] = []
    for bit in range(64):
        if mask & (1 << bit):
            terms.append(f"{var}[{bit}]")
    if mask & (1 << CONST_BIT):
        terms.append("1'b1")

    if not terms:
        return "1'b0"
    return " ^ ".join(terms)


def generate_bsv_function(name: str, matrix: list[int]) -> str:
    """Generate a BSV function from a 32-element XOR matrix."""
    lines: list[str] = []
    lines.append(f"function Bit#(32) {name}(Bit#(64) d);")

    bit_names: list[str] = []
    for i in range(32):
        bname = f"b{i}"
        bit_names.append(bname)
        expr = bitmask_to_xor_expr(matrix[i])
        lines.append(f"    Bit#(1) {bname} = {expr};")

    # Build return value: {b31, b30, ..., b1, b0}
    concat = ", ".join(reversed(bit_names))
    lines.append(f"    return {{{concat}}};")
    lines.append("endfunction")
    return "\n".join(lines)


def generate_bsv_package(output_path: Path | None = None) -> str:
    """Generate the full CRC32.bsv package with XOR network functions."""
    mat32 = compute_xor_matrix(CRC32_POLY)
    mat32c = compute_xor_matrix(CRC32C_POLY)

    func32 = generate_bsv_function("crc32", mat32)
    func32c = generate_bsv_function("crc32c", mat32c)

    # Compute stats
    def stats(mat: list[int]) -> tuple[int, int, int]:
        counts: list[int] = []
        for m in mat:
            c = bin(m & ((1 << 64) - 1)).count("1")
            if m & (1 << CONST_BIT):
                c += 1
            counts.append(c)
        return min(counts), max(counts), sum(counts)

    min32, max32, total32 = stats(mat32)
    min32c, max32c, total32c = stats(mat32c)

    bsv = f"""\
package CRC32;

// ============================================================
// CRC32 and CRC32C as pure XOR networks for 8-byte input.
//
// Generated by scripts/gen_crc32_xor.py
// Each output bit is a fixed XOR of input bits — no muxes.
// Logic depth: ~log2(max_terms) levels of XOR gates.
//
// CRC32  (IEEE 802.3, poly 0x04C11DB7):
//   XOR terms per bit: {min32}..{max32}, total: {total32}
//
// CRC32C (Castagnoli, poly 0x1EDC6F41):
//   XOR terms per bit: {min32c}..{max32c}, total: {total32c}
// ============================================================

{func32}

{func32c}

endpackage
"""

    if output_path:
        output_path.write_text(bsv, encoding="utf-8")
        print(f"Generated {output_path}")
        print(f"  CRC32:  {min32}-{max32} XOR terms/bit, {total32} total")
        print(f"  CRC32C: {min32c}-{max32c} XOR terms/bit, {total32c} total")

    return bsv


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Generate CRC32 XOR network BSV")
    parser.add_argument(
        "--output",
        default="../hw/CRC32.bsv",
        help="Output BSV file path (default: ../hw/CRC32.bsv)",
    )
    args = parser.parse_args()

    generate_bsv_package(Path(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
